"""
{
    "OLTP column name": "OLAP column name",
    ...
}
"""
ops_dwh_transactions_map = {
    "rental_id": "transactionId",
    "rental_date": "transactionDate",
    "return_date": "returnDate",
    "customer_id": "customerId",
    "first_name": "customerName",
    "last_name": "customerSurname",
    "email": "customerEmail",
    "activebool": "activeBool",
    "create_date": "customerJoinDate",
    "address_id": "customerAddressId",
    "address": "customerAddress",
    "address2": "customerAddress2",
    "district": "customerDistrict",
    "postal_code": "customerPostal",
    "phone": "customerPhone",
    "city_id": "customerCityId",
    "city": "customerCity",
    "payment_id": "paymentId",
    "amount": "paymentAmount",
    "payment_date": "paymentDate",
    "inventory_id": "inventoryId",
    "category_name": "categoryName",
    "film_id": "filmId",
    "title": "filmTitle",
    "description": "filmDesc",
    "release_year": "filmRelease",
    "language_id": "filmLanguage",
    "rental_duration": "transactionDuration",
    "rental_rate": "transactionRate",
    "length": "filmLength",
    "replacement_cost": "filmCost",
    "rating": "filmRating",
    "last_update": "filmUpdate",
    "special_features": "filmFeatures",
    "fulltext": "filmFulltext",
    "report_date": "reportDate",
    "partition_date": "partitionDate",
}
